title: Frida Kahlo 
baseURL: https://github.com/Mandarinka89/hugo-start
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Domovská stránka 
      url: /
      weight: 10
    - name: Archiv 
      identifier: post
      url: /post/
      weight: 

params:
  description: Moje první webová stránka.
  authors: MANDARINKA
